version: "3"
services:
  boathouse-calculator-dev:
    image: rregistry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-v2-vscode-vmlc:all-version
    runtime: sysbox-runc
    hostname: dev-container
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123       
    volumes:
      - .:/home/project
    ports:
      - 6822:22
    networks:
      - smartide-network  

networks:
  smartide-network:
    external: true